## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [441]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [442]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),
    ('h_a', nn.Sigmoid()),
    ('output', nn.Linear(2, 2)),
    ('h_a', nn.Sigmoid())
]))

model2 = nn.Sequential(OrderedDict([
    ('fc1', nn.Linear(2, 5)),
    ('relu1', nn.ReLU()),
    ('fc2', nn.Linear(5, 3)),
    ('relu2', nn.ReLU()),
    ('fc3', nn.Linear(3, 2)),
    ('relu3', nn.ReLU())
]))

model3 = nn.Sequential(OrderedDict([
    ('fc1', nn.Linear(2, 5)),
    ('relu1', nn.ReLU()),
    ('fc2', nn.Linear(5, 3)),
    ('relu2', nn.ReLU()),
    ('fc3', nn.Linear(3, 2)),
    ('sigmoid', nn.Sigmoid())
]))

# the database contains 0 and 1 because we must add two bits

# 3 layers: the input and output layers and one hidden layer
# the activation function is the sigmoid function
# the loss function is

# ==============================================================================================================================================

# for MODEL 1:
# input layer has 2 neurons, hidden layer has 2 neurons and output layer has 1 neuron

# for MODEL 2:
# input layer has 2 neurons, hidden layer has 4 neurons and output layer has 1 neuron

# for MODEL 3:
# input layer has 2 neurons, hidden layer has 8 neurons and output layer has 1 neuron

# ==============================================================================================================================================

# MODEL 1 is a neural network with:
# - one hidden layer of two nodes (input size 2, output size 2)
# - an output layer of one node (input size 2, output size 1).

# MODEL 2 is a neural network with: three fully connected layers (also known as linear layers) with ReLU activation functions.
# - the first layer has input size 2 and output size 5.
# - the second layer has input size 5 and output size 3
# - the third layer has input size 3 and output size 1.


# MODEL3 is similar to MODEL2 but with a sigmoid activation function applied to the output of the final layer instead of a ReLU function.

# Overall, model2 and model3 have the same architecture with the only difference being the activation function used in the final layer.

In [443]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (h_a): Sigmoid()
  (output): Linear(in_features=2, out_features=2, bias=True)
)
Sequential(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=5, out_features=3, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=3, out_features=2, bias=True)
  (relu3): ReLU()
)
Sequential(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=5, out_features=3, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=3, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)


In [444]:
# your code here
#data_in = torch.tensor( ...
#contains all the possible combinations of bits(0, 1)
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [445]:
# your code here
# data_target = torch.tensor( ...
# contains all the possible results of adding 2 bits
data_target = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float32)

print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [446]:
# your code here
# criterion = 
# optimizer =

criterion = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1) # calculates gradients with learning rate 0.1
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

In [447]:
# your code here
# Train the model

num_epochs = 1000

# Train MODEL1 for 1000 epochs:
print('MODEL 1')
for epoch in range(num_epochs):
    output = model1(data_in) # Forward pass
    loss = criterion(output, data_target) # Calculate the loss
    optimizer1.zero_grad() # Backward pass and optimization
    loss.backward()
    optimizer1.step()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}") # Print the loss every 100 epochs


# Train MODEL2 for 1000 epochs:
print('MODEL 2')
for epoch in range(num_epochs):
    output = model2(data_in) # Forward pass
    loss = criterion(output, data_target) # Calculate the loss
    optimizer2.zero_grad() # Backward pass and optimization
    loss.backward()
    optimizer2.step()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}") # Print the loss every 100 epochs


# Train the model 3 for 1000 epochs
print('MODEL 3')
for epoch in range(num_epochs):
    output = model3(data_in) # Forward pass
    loss = criterion(output, data_target) # Calculate the loss
    optimizer3.zero_grad() # Backward pass and optimization
    loss.backward()
    optimizer3.step()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}") # Print the loss every 100 epochs

MODEL 1
Epoch [100/1000], Loss: 0.2192
Epoch [200/1000], Loss: 0.2167
Epoch [300/1000], Loss: 0.2137
Epoch [400/1000], Loss: 0.2092
Epoch [500/1000], Loss: 0.2024
Epoch [600/1000], Loss: 0.1931
Epoch [700/1000], Loss: 0.1830
Epoch [800/1000], Loss: 0.1742
Epoch [900/1000], Loss: 0.1677
Epoch [1000/1000], Loss: 0.1632
MODEL 2
Epoch [100/1000], Loss: 0.3041
Epoch [200/1000], Loss: 0.2615
Epoch [300/1000], Loss: 0.2502
Epoch [400/1000], Loss: 0.2500
Epoch [500/1000], Loss: 0.2500
Epoch [600/1000], Loss: 0.2500
Epoch [700/1000], Loss: 0.2500
Epoch [800/1000], Loss: 0.2500
Epoch [900/1000], Loss: 0.2500
Epoch [1000/1000], Loss: 0.2500
MODEL 3
Epoch [100/1000], Loss: 0.2209
Epoch [200/1000], Loss: 0.2155
Epoch [300/1000], Loss: 0.2124
Epoch [400/1000], Loss: 0.2077
Epoch [500/1000], Loss: 0.1999
Epoch [600/1000], Loss: 0.1851
Epoch [700/1000], Loss: 0.1571
Epoch [800/1000], Loss: 0.1136
Epoch [900/1000], Loss: 0.0751
Epoch [1000/1000], Loss: 0.0517


In [448]:
# your code here
# visualize the results

import matplotlib.pyplot as plt

# For MODEL 1:
output = model1(data_in)
predictions = (output >= 0.5).float() # Convert the output probabilities to binary predictions
print("Model 1's predictions:") # Print the model's predictions
print(predictions)

# For MODEL 2:
output = model2(data_in)
predictions = (output >= 0.5).float() # Convert the output probabilities to binary predictions
print("Model 2's predictions:") # Print the model's predictions
print(predictions)

# For MODEL 3:
output = model3(data_in)
predictions = (output >= 0.5).float() # Convert the output probabilities to binary predictions
print("Model 3's predictions:") # Print the model's predictions
print(predictions)

Model 1's predictions:
tensor([[0., 0.],
        [0., 0.],
        [0., 1.],
        [1., 1.]])
Model 2's predictions:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]])
Model 3's predictions:
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [449]:
# your code here
# print model weights

accuracies = []
models = [model1, model2, model3]
for model in models:
    model.eval()
    with torch.no_grad():
        outputs = model(data_in)
        predicted = (outputs >= 0.5).float()
        accuracy = (predicted == data_target).float().mean()
        accuracies.append(accuracy)

    print("Accuracy: {:.2f}%".format(accuracy.item() * 100))

# Select the best-performing model
best_model = models[accuracies.index(max(accuracies))]

print('Model ' + str(accuracies.index(max(accuracies)) + 1) + ' is the best!')

Accuracy: 75.00%
Accuracy: 75.00%
Accuracy: 100.00%
Model 3 is the best!
